### ISSUE TITLE
Compilation fails with ESPHome 2025.12.0 - address_str().c_str() errors

### ISSUE THREAD

**Issue by xXAzazelXx** [gurrier/esphome-powerpal_ble#57]
**Description**
Environment:

ESPHome Version: 2025.12.0
Board: esp32-s3-devkitc-1
Framework: esp-idf
Component ref: 1.2

**Problem**:
The powerpal_ble component fails to compile with ESPHome 2025.12.0 due to breaking changes in the ESPHome API. The address_str() method now returns const char* directly instead of a string object, causing compilation errors when .c_str() is called on it.

**Error Log**:
src/esphome/components/powerpal_ble/powerpal_ble.cpp:294:98: error: request for member 'c_str' in '((esphome::powerpal_ble::Powerpal*)this)->esphome::powerpal_ble::Powerpal::esphome::ble_client::BLEClientNode.esphome::ble_client::BLEClientNode::parent_->esphome::ble_client::BLEClient::esphome::esp32_ble_client::BLEClientBase.esphome::esp32_ble_client::BLEClientBase::address_str()', which is of non-class type 'const char*'
  294 |       ESP_LOGD(TAG, "[%s] ESP_GATTC_READ_CHAR_EVT (Received READ)", this->parent_->address_str().c_str());

**Affected Lines:**
The following lines in powerpal_ble.cpp are affected:

Line 294
Line 319
Line 371
Line 416
Line 444
Line 450
Line 455
Line 482

All instances use the pattern: this->parent_->address_str().c_str()

**Comment by HSB-collab** [comment]
I have the same issue

**Comment by bdleung** [comment]
Same for 2025.12.1 :)
